{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-core-marker",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rcm-core-marker-0.1.0.jar",
          "url": "rcm-core-marker-0.1.0.jar",
          "size": 5377,
          "sha512": "5af840dd8b619e276e2ce7af4793391e75ab786999991f3062d9e5378bc78383b96c36db1207cdea8a4a929b1fb20748255907622a207df9d62f4e7c05050f11",
          "sha256": "58c7685acfe79d7e2ad1d5b63acbe07299efe24e78a8fc14d0fb5b8373a0fed5",
          "sha1": "29ed79f6882a09c88d6eb2e12bebba0407eb3f80",
          "md5": "0518e726a86cca2544dd104e3bbe22fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "rcm-core-marker-0.1.0.jar",
          "url": "rcm-core-marker-0.1.0.jar",
          "size": 5377,
          "sha512": "5af840dd8b619e276e2ce7af4793391e75ab786999991f3062d9e5378bc78383b96c36db1207cdea8a4a929b1fb20748255907622a207df9d62f4e7c05050f11",
          "sha256": "58c7685acfe79d7e2ad1d5b63acbe07299efe24e78a8fc14d0fb5b8373a0fed5",
          "sha1": "29ed79f6882a09c88d6eb2e12bebba0407eb3f80",
          "md5": "0518e726a86cca2544dd104e3bbe22fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-core-marker-0.1.0-sources.jar",
          "url": "rcm-core-marker-0.1.0-sources.jar",
          "size": 8870,
          "sha512": "7fa9c9f9b8f5dcedb308ea2ab5d77f3ce955454e43d1b31a2d8a1eba68e5a2e7f0cecea304760ac48589b766670e5344ddec6a2b3c32b2f6f49b412574e681bc",
          "sha256": "7ee739eade577238c8942d58ffe7fb68e5528f6c5464a047be9a62a32463b0a1",
          "sha1": "9976f4df972611c74f2da1fa358df97fe2dbdf88",
          "md5": "b0a6da1c0b22fcaa01579c1851efae65"
        }
      ]
    }
  ]
}
