{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-test",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rcm-starter-test-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-test-0.1.0-SNAPSHOT.jar",
          "size": 1417,
          "sha512": "0b0ec5d34ccc6c58f95a36e14ad0b6fba655fcd9653935c0fab5ac5347ca46c333a0605319666f1c415b16f3cb0cf2ce01041f3e0640b804f7272bcba2efbf87",
          "sha256": "11337780036b5eac6e83bc0aba92e82e8ff45c132fc23f41097f71289249a029",
          "sha1": "c621a24e38eb29873e9e7a639ba0ee4c59bf105d",
          "md5": "7f5a154a2de00868596f51228c502d94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-test-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-test-0.1.0-SNAPSHOT.jar",
          "size": 1417,
          "sha512": "0b0ec5d34ccc6c58f95a36e14ad0b6fba655fcd9653935c0fab5ac5347ca46c333a0605319666f1c415b16f3cb0cf2ce01041f3e0640b804f7272bcba2efbf87",
          "sha256": "11337780036b5eac6e83bc0aba92e82e8ff45c132fc23f41097f71289249a029",
          "sha1": "c621a24e38eb29873e9e7a639ba0ee4c59bf105d",
          "md5": "7f5a154a2de00868596f51228c502d94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-test-0.1.0-SNAPSHOT-sources.jar",
          "url": "rcm-starter-test-0.1.0-SNAPSHOT-sources.jar",
          "size": 1495,
          "sha512": "85429ec00796f5cce77844a7b803bb1288647d4535b7eeb58d909f949214fa306c6dd49abf9e54a39727a64fff01a5df4b8093e3289421575c712db9304dc9ad",
          "sha256": "c90ceca166b77095aa534e211cda0fbe91d3e006f32468727106200f471a906e",
          "sha1": "cd085b600b1612f081aa914af8440d56cc47495e",
          "md5": "d2be4717f42b59dbf7d6009e27102914"
        }
      ]
    }
  ]
}
