{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-web",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rcm-starter-web-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-web-0.1.0-SNAPSHOT.jar",
          "size": 1510,
          "sha512": "25f232b849c3d010806f438f61d185a462dbc7dc497c3acafd7ae7e5c7ac32d6505010a4f813601b6988f687de2b8b63d119aa6031d44c701e1fe696e078f095",
          "sha256": "d54b4bf9efef4044418b10e75c08b8075f786deb4049d37ed466ca5706d3bad9",
          "sha1": "89aa7fa316930ba9c07e83d0e4f6701ef622989b",
          "md5": "6021639d6bcc329b39f3737b626ba44a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-web-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-web-0.1.0-SNAPSHOT.jar",
          "size": 1510,
          "sha512": "25f232b849c3d010806f438f61d185a462dbc7dc497c3acafd7ae7e5c7ac32d6505010a4f813601b6988f687de2b8b63d119aa6031d44c701e1fe696e078f095",
          "sha256": "d54b4bf9efef4044418b10e75c08b8075f786deb4049d37ed466ca5706d3bad9",
          "sha1": "89aa7fa316930ba9c07e83d0e4f6701ef622989b",
          "md5": "6021639d6bcc329b39f3737b626ba44a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-web-0.1.0-SNAPSHOT-sources.jar",
          "url": "rcm-starter-web-0.1.0-SNAPSHOT-sources.jar",
          "size": 1548,
          "sha512": "6671af339beabe036927867415b7b722ef53433bc75afbea45102f90a363b3fcae4d7df2aef28aae68cbf4251d78cdce2e31c93f7da91ebd2fd4b178896887a8",
          "sha256": "02597a2df446c127bce4190b0ef0ae577832582f3872e294a8a722a356f8d05f",
          "sha1": "256954b8e5ee777d56c59c32b1815e04a45982d6",
          "md5": "afaba72c33cddb73b25e3ab1ff4ff24f"
        }
      ]
    }
  ]
}
