{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-core-enumtype",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rcm-core-enumtype-0.1.0-SNAPSHOT.jar",
          "url": "rcm-core-enumtype-0.1.0-SNAPSHOT.jar",
          "size": 13188,
          "sha512": "081e9a3104a76b9d70fb6f693b2602d801f7040d365671725f766ff1d6dbd9f5bc5ff2038fcc58adac7b4b427a2a925edb1bb0f599df8f544bc9a4b58d4e43b0",
          "sha256": "138bece22510241974c0239b5dc5708cb250857d0348075c4df8555b6e5d1a1b",
          "sha1": "7333d3c17874b8f26c9744a5001f4737f3e32c74",
          "md5": "ae8a3ab428eb109afb7cce20729b0481"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "rcm-core-enumtype-0.1.0-SNAPSHOT.jar",
          "url": "rcm-core-enumtype-0.1.0-SNAPSHOT.jar",
          "size": 13188,
          "sha512": "081e9a3104a76b9d70fb6f693b2602d801f7040d365671725f766ff1d6dbd9f5bc5ff2038fcc58adac7b4b427a2a925edb1bb0f599df8f544bc9a4b58d4e43b0",
          "sha256": "138bece22510241974c0239b5dc5708cb250857d0348075c4df8555b6e5d1a1b",
          "sha1": "7333d3c17874b8f26c9744a5001f4737f3e32c74",
          "md5": "ae8a3ab428eb109afb7cce20729b0481"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-core-enumtype-0.1.0-SNAPSHOT-sources.jar",
          "url": "rcm-core-enumtype-0.1.0-SNAPSHOT-sources.jar",
          "size": 11770,
          "sha512": "c2f994bc41f1f75e480905bfdc62f622c0e28f33eed4ab237c1735bf4cb059bea2e9c997f0cd7ae61e9ac34b1ec81c3b7656bd0bcf0e96fbdd08c0a62b2bfab1",
          "sha256": "866fb62022fa3299103e30d7a8140d195b7f385497835149c6f75cd1ec048f4f",
          "sha1": "705ec9be34f487ca0661cc364748cc24a76ef2ce",
          "md5": "07776f1dcf917ead02c4b1474276fb37"
        }
      ]
    }
  ]
}
