{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-security",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-oauth2-resource-server"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis"
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop"
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver"
        },
        {
          "group": "org.springframework",
          "module": "spring-web"
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-security-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-security-0.1.0-SNAPSHOT.jar",
          "size": 112620,
          "sha512": "c249f6d695568a13bedb07f5f452f1eb473a455309035353bc4a7f2e6e16fa60ee76a27d5b493c6c1401c7114986bb6e8080c56e0871a86f129892b37a1f8e16",
          "sha256": "d0078c763dd096c209b2ec6404bbd8e79620fc5bc620d8dfdc295992c60d797b",
          "sha1": "498af6fe7458ec4a1fa8fc9ff3f5a57cc0bc5026",
          "md5": "a7a0ecb899ce59ec1202c035484ca85a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-oauth2-resource-server"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis"
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop"
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver"
        },
        {
          "group": "org.springframework",
          "module": "spring-web"
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-security-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-security-0.1.0-SNAPSHOT.jar",
          "size": 112620,
          "sha512": "c249f6d695568a13bedb07f5f452f1eb473a455309035353bc4a7f2e6e16fa60ee76a27d5b493c6c1401c7114986bb6e8080c56e0871a86f129892b37a1f8e16",
          "sha256": "d0078c763dd096c209b2ec6404bbd8e79620fc5bc620d8dfdc295992c60d797b",
          "sha1": "498af6fe7458ec4a1fa8fc9ff3f5a57cc0bc5026",
          "md5": "a7a0ecb899ce59ec1202c035484ca85a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-security-0.1.0-SNAPSHOT-sources.jar",
          "url": "rcm-starter-security-0.1.0-SNAPSHOT-sources.jar",
          "size": 83506,
          "sha512": "f3730bb0e774ff81a6f02558308c6b4436f9d09fd68cd4c952f486720983f9438425aba0cd1fe6692aff0a22014db511e2f0bd7c0bf071dae40da98892ce66c3",
          "sha256": "122e0a81feb6f7f4d8748f7cc39104319107698b8d912dda8d111de7c6681ebc",
          "sha1": "92e66259645f312960ccf037da273aa1dbfc112a",
          "md5": "d0944c32cf9c93510127721d1f8765ea"
        }
      ]
    }
  ]
}
