{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-security",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rcm-starter-security-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-security-0.1.0-SNAPSHOT.jar",
          "size": 1518,
          "sha512": "a1402653925f74e80449769e5b34a496b12ccd91ef118d0efc4f6a19bea8c3a1697ef9a4d9894106363994474393b8d1a14dc05d02ca5b868223eb56b0479087",
          "sha256": "6f7c039c15f3f947473cdd7baea4e9f178e0d20a85f380c20af8d00aee4564fc",
          "sha1": "bfaf3b663ad1c0d9d95c1fcde7c29d001b624963",
          "md5": "cacbfdead827965224b310fc2f37c833"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-security-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-security-0.1.0-SNAPSHOT.jar",
          "size": 1518,
          "sha512": "a1402653925f74e80449769e5b34a496b12ccd91ef118d0efc4f6a19bea8c3a1697ef9a4d9894106363994474393b8d1a14dc05d02ca5b868223eb56b0479087",
          "sha256": "6f7c039c15f3f947473cdd7baea4e9f178e0d20a85f380c20af8d00aee4564fc",
          "sha1": "bfaf3b663ad1c0d9d95c1fcde7c29d001b624963",
          "md5": "cacbfdead827965224b310fc2f37c833"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-security-0.1.0-SNAPSHOT-sources.jar",
          "url": "rcm-starter-security-0.1.0-SNAPSHOT-sources.jar",
          "size": 1597,
          "sha512": "357d669547685c1cf4d59bcec90a9d43b136b2b5f205775ef544532fdf47190f063bf51b12ea47da78c6a77388bab89195100bf8e0fa04ab877b1ddfeb50844d",
          "sha256": "c470de6a6988b0af416a7d0270c63859cad5120008df2e06f0c7f99dcb2b1fe5",
          "sha1": "ac3f7df62a705b546e05480d73d9fa6d0a7fbb9a",
          "md5": "c4b5d99ecc01ba77f6ccfdc0aca7ee36"
        }
      ]
    }
  ]
}
