{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-jpa",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-search",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "io.hypersistence",
          "module": "hypersistence-tsid",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-jpa-0.1.0-SNAPSHOT.jar",
          "size": 163645,
          "sha512": "4d9b3a54602bc44fe78180b5a8958c7ff5f6b69918fafbd94106231d649cf0fed7e2cb812e96959dac0d2429fe244e6158290079fc9666db6dd24d9d162aa2ac",
          "sha256": "b5900894d91eb141aedbf825d0614213997681a0b8cc704b99a76ff46cf106dd",
          "sha1": "f9dbeb7b87aa73b070c699002cfc5d3628e4cac9",
          "md5": "2b8c36d894eb0d8be1f897e3edcdcd89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-search",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "io.hypersistence",
          "module": "hypersistence-tsid",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-jpa-0.1.0-SNAPSHOT.jar",
          "size": 163645,
          "sha512": "4d9b3a54602bc44fe78180b5a8958c7ff5f6b69918fafbd94106231d649cf0fed7e2cb812e96959dac0d2429fe244e6158290079fc9666db6dd24d9d162aa2ac",
          "sha256": "b5900894d91eb141aedbf825d0614213997681a0b8cc704b99a76ff46cf106dd",
          "sha1": "f9dbeb7b87aa73b070c699002cfc5d3628e4cac9",
          "md5": "2b8c36d894eb0d8be1f897e3edcdcd89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0-SNAPSHOT-sources.jar",
          "url": "rcm-starter-jpa-0.1.0-SNAPSHOT-sources.jar",
          "size": 135423,
          "sha512": "4c83fe353b3ccc2759560fb375e4c8eb07a9cd999e05cd155314d1c9b08778736a7d25a3adb19da88350c1b14539616f0b7a29b0104fcffc3ac7d1849d9ef695",
          "sha256": "25b86174383d9cf5cd37a83ed2e2d6ad68f72580fd3f276cd842321a2daa33b4",
          "sha1": "65e4f5f0be4dfcd54d38090dcd5563d0a4c4e881",
          "md5": "e9a74376dae8544a673ac6996642d753"
        }
      ]
    }
  ]
}
