{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-apt",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rcm-apt-0.1.0-SNAPSHOT.jar",
          "url": "rcm-apt-0.1.0-SNAPSHOT.jar",
          "size": 39791,
          "sha512": "3730f5f95ea7d7c5cabdcf1577258a3cb763e9d2d871f1848f3ff08505715bc9e9db5cb8b06cf5c2de1026af2b7753cf668d4d15a3ea46291735024ce236d75a",
          "sha256": "0df6cc22043cd6bb825761a6b304c38a6c9dd60159d228b29c59485a23414cf5",
          "sha1": "85b30126c786ae200e8ff482e1eb00172b83dead",
          "md5": "64372d8b6fb1a355de5a4d6258d81ae2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-search",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "rcm-apt-0.1.0-SNAPSHOT.jar",
          "url": "rcm-apt-0.1.0-SNAPSHOT.jar",
          "size": 39791,
          "sha512": "3730f5f95ea7d7c5cabdcf1577258a3cb763e9d2d871f1848f3ff08505715bc9e9db5cb8b06cf5c2de1026af2b7753cf668d4d15a3ea46291735024ce236d75a",
          "sha256": "0df6cc22043cd6bb825761a6b304c38a6c9dd60159d228b29c59485a23414cf5",
          "sha1": "85b30126c786ae200e8ff482e1eb00172b83dead",
          "md5": "64372d8b6fb1a355de5a4d6258d81ae2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-apt-0.1.0-SNAPSHOT-sources.jar",
          "url": "rcm-apt-0.1.0-SNAPSHOT-sources.jar",
          "size": 19062,
          "sha512": "7d540737fe6391f97005c522d97fdd8a472a9d35f7f4d53ebba95d67e82bb9705e6d9b0e614e6e24a419327a8181ee1ed429353b3f09076565a41b48803c4fda",
          "sha256": "3377834a223ef123ea169582eaaba3e216a8430190776d4a2d3cd32f2a509318",
          "sha1": "131aac3e0c105ad38fa30d248f4a55987dde5727",
          "md5": "ca9c0b835bf61f29bb25d81c69ce1547"
        }
      ]
    }
  ]
}
