{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "showcase",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "showcase-0.1.0-plain.jar",
          "url": "showcase-0.1.0-plain.jar",
          "size": 211436,
          "sha512": "f961c83cf7946da7c52e19c60c9fd068d2482d9e33a9a20aa709b05aff2d3ba2066b58c43a37ed3bac89ac0d8105d91a606adde721e43673ec00d8fb2271cd73",
          "sha256": "1f610f4ec6174c9740d2bdcd87616d7f1536f52a7b43cc2e37d209062aaf56be",
          "sha1": "d70e4f9bfea94668e27be984248d001762618ace",
          "md5": "7b2dde4dabf7505cff0119da1dc170e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-web",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-security",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-external",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-featureflag",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-kr",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-notification",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-storage",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-document",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa-i18n",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-asset",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-search-elasticsearch",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-workflow",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core"
        },
        {
          "group": "org.postgresql",
          "module": "postgresql"
        },
        {
          "group": "com.h2database",
          "module": "h2"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql"
        }
      ],
      "files": [
        {
          "name": "showcase-0.1.0-plain.jar",
          "url": "showcase-0.1.0-plain.jar",
          "size": 211436,
          "sha512": "f961c83cf7946da7c52e19c60c9fd068d2482d9e33a9a20aa709b05aff2d3ba2066b58c43a37ed3bac89ac0d8105d91a606adde721e43673ec00d8fb2271cd73",
          "sha256": "1f610f4ec6174c9740d2bdcd87616d7f1536f52a7b43cc2e37d209062aaf56be",
          "sha1": "d70e4f9bfea94668e27be984248d001762618ace",
          "md5": "7b2dde4dabf7505cff0119da1dc170e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "showcase-0.1.0-sources.jar",
          "url": "showcase-0.1.0-sources.jar",
          "size": 158558,
          "sha512": "09db6709c0036a18404a03b90832682e1c7a71c8419f4d52f0a23b329a61cdf48707e433db26a04e3b111dffa695507dd128e981b7ef45ea6d3ff76a987f9160",
          "sha256": "193c9a7e6f0fd3f88e93c28116f4e9fd5100713fc6b2beb1b5a079fa74ca97d4",
          "sha1": "cb3a4423e7ef21c971e987ac9a3ff19904b11b51",
          "md5": "f86aa520402e951cd8d937c59b948331"
        }
      ]
    }
  ]
}
