{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "bom",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "4.0.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.rchemist",
          "module": "rcm-starter-web",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-security",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-external",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-test",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "4.0.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.rchemist",
          "module": "rcm-starter-web",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-security",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-external",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-test",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ]
    }
  ]
}
