{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-external",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rcm-starter-external-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-external-0.1.0-SNAPSHOT.jar",
          "size": 1502,
          "sha512": "ce79d86bc97cceef56970f6263a6df5434842c373e4a4b87c146617796508fe26e090e8fe69113ccd32dd157e3cc7c8d5580ba3b74559a3f71c9e40e03ba8f9e",
          "sha256": "d687a1a7286558de28676de5bfa03bd60e11c14d59798f2b4942feff90512500",
          "sha1": "8b0ac297e049acd2380e3eabab31b8f99119775f",
          "md5": "b0d598a662070a3b5cda4474c301692f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-external-0.1.0-SNAPSHOT.jar",
          "url": "rcm-starter-external-0.1.0-SNAPSHOT.jar",
          "size": 1502,
          "sha512": "ce79d86bc97cceef56970f6263a6df5434842c373e4a4b87c146617796508fe26e090e8fe69113ccd32dd157e3cc7c8d5580ba3b74559a3f71c9e40e03ba8f9e",
          "sha256": "d687a1a7286558de28676de5bfa03bd60e11c14d59798f2b4942feff90512500",
          "sha1": "8b0ac297e049acd2380e3eabab31b8f99119775f",
          "md5": "b0d598a662070a3b5cda4474c301692f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-external-0.1.0-SNAPSHOT-sources.jar",
          "url": "rcm-starter-external-0.1.0-SNAPSHOT-sources.jar",
          "size": 1605,
          "sha512": "acd1f082ff92e227650caf0f07630c4204d46b6df4d475f1e420ffdc470c1538a560732900e15cb868c77e0b1f1a805264c4b3179459c0f35af9671ad285a94b",
          "sha256": "295fd72a72a692a2094d5abb9a3831c13f5705474ae13a3a08c0bf08ed9b3c62",
          "sha1": "5bbae2e14d73b1fd4edfc70af83e8bf1d2cdc8a4",
          "md5": "7a17d58d6fcdb7fafcb2dc705db480ec"
        }
      ]
    }
  ]
}
