{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "showcase",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "showcase-0.1.0-SNAPSHOT-plain.jar",
          "url": "showcase-0.1.0-SNAPSHOT-plain.jar",
          "size": 213257,
          "sha512": "7580c8524b7eb352291ee6fc49bcbb864bb19a31f3b9c3b9ac41936a4bc2af0e9aa46d8eaec9c5ea5ef9a9b852fa90d6de6286ee9a8ef6d0405464318bdcfe9f",
          "sha256": "04c6546720740a6f4e6fe041a41dc94877c3f5f7e45701d63941a6f20d16b86f",
          "sha1": "dadc06c162d5062e81271cc16097f6b9caf5e641",
          "md5": "7c91d3e35e7efd728d7f28b602d9fa6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-web",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-security",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-external",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-featureflag",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-kr",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-notification",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-storage",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-document",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa-i18n",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-asset",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-search-elasticsearch",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-workflow",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core"
        },
        {
          "group": "org.postgresql",
          "module": "postgresql"
        },
        {
          "group": "com.h2database",
          "module": "h2"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql"
        }
      ],
      "files": [
        {
          "name": "showcase-0.1.0-SNAPSHOT-plain.jar",
          "url": "showcase-0.1.0-SNAPSHOT-plain.jar",
          "size": 213257,
          "sha512": "7580c8524b7eb352291ee6fc49bcbb864bb19a31f3b9c3b9ac41936a4bc2af0e9aa46d8eaec9c5ea5ef9a9b852fa90d6de6286ee9a8ef6d0405464318bdcfe9f",
          "sha256": "04c6546720740a6f4e6fe041a41dc94877c3f5f7e45701d63941a6f20d16b86f",
          "sha1": "dadc06c162d5062e81271cc16097f6b9caf5e641",
          "md5": "7c91d3e35e7efd728d7f28b602d9fa6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "showcase-0.1.0-SNAPSHOT-sources.jar",
          "url": "showcase-0.1.0-SNAPSHOT-sources.jar",
          "size": 158687,
          "sha512": "1cb9e8280bd99c98fa36094c09a6ffc019a742b02bd76d29c221abdaae515fca0ac1a196922e7cbdedffe50437fa09a3bbe7ecbc872dff92c7d91121730db64d",
          "sha256": "2a4f32cb567a4a2feb1e93137843192f4f16892e0d31b90cd1fa488c82638ace",
          "sha1": "8d53713be7e79c10018bba2ee2373d55fedd5a3d",
          "md5": "f084900e95554fc46e553dba2c1b0437"
        }
      ]
    }
  ]
}
