{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "showcase",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "showcase-0.1.0-SNAPSHOT-plain.jar",
          "url": "showcase-0.1.0-SNAPSHOT-plain.jar",
          "size": 211323,
          "sha512": "5a52fe7102c61d1c853abc813597b19e523203d96fee3962d67bacac93b25dd1ebbb0f1f8c732e11f5dc63d18bcb78add10997d38a4923a14b565b3588294b3a",
          "sha256": "ac494a622ab2d7f2b811f0081514393d499bea032c515a937b6b0e6a69fa7127",
          "sha1": "6f76c9dcd75e49d2a3f8a77d1e98b977a4fcdc40",
          "md5": "19b5d58fd260380847dd8ff7c77e986c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-web",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-security",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-external",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-featureflag",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-kr",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-notification",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-storage",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-document",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa-i18n",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-asset",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-search-elasticsearch",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-workflow",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core"
        },
        {
          "group": "org.postgresql",
          "module": "postgresql"
        },
        {
          "group": "com.h2database",
          "module": "h2"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql"
        }
      ],
      "files": [
        {
          "name": "showcase-0.1.0-SNAPSHOT-plain.jar",
          "url": "showcase-0.1.0-SNAPSHOT-plain.jar",
          "size": 211323,
          "sha512": "5a52fe7102c61d1c853abc813597b19e523203d96fee3962d67bacac93b25dd1ebbb0f1f8c732e11f5dc63d18bcb78add10997d38a4923a14b565b3588294b3a",
          "sha256": "ac494a622ab2d7f2b811f0081514393d499bea032c515a937b6b0e6a69fa7127",
          "sha1": "6f76c9dcd75e49d2a3f8a77d1e98b977a4fcdc40",
          "md5": "19b5d58fd260380847dd8ff7c77e986c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "showcase-0.1.0-SNAPSHOT-sources.jar",
          "url": "showcase-0.1.0-SNAPSHOT-sources.jar",
          "size": 158558,
          "sha512": "09db6709c0036a18404a03b90832682e1c7a71c8419f4d52f0a23b329a61cdf48707e433db26a04e3b111dffa695507dd128e981b7ef45ea6d3ff76a987f9160",
          "sha256": "193c9a7e6f0fd3f88e93c28116f4e9fd5100713fc6b2beb1b5a079fa74ca97d4",
          "sha1": "cb3a4423e7ef21c971e987ac9a3ff19904b11b51",
          "md5": "f86aa520402e951cd8d937c59b948331"
        }
      ]
    }
  ]
}
