{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-jpa-i18n",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-starter-web",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-jpa-i18n-0.1.0.jar",
          "url": "rcm-starter-jpa-i18n-0.1.0.jar",
          "size": 16330,
          "sha512": "1273eac7b064f649c393a6783bb04e70d169369c3e40e5cd20681aca374f8c6e32311bec56c110db8a0725bd1bed5ab0195125faa14a44817d332047fa66e095",
          "sha256": "5c24a0c75865c04e8953c49e45904a44f5a9dfb6bc210b42a5b924ee78e788a1",
          "sha1": "b5d1d682e8925740f068a6d014e98d6f586d2942",
          "md5": "62c4029c2f373f625d6b1b21f62af5ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-web",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-starter-jpa",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-jpa-i18n-0.1.0.jar",
          "url": "rcm-starter-jpa-i18n-0.1.0.jar",
          "size": 16330,
          "sha512": "1273eac7b064f649c393a6783bb04e70d169369c3e40e5cd20681aca374f8c6e32311bec56c110db8a0725bd1bed5ab0195125faa14a44817d332047fa66e095",
          "sha256": "5c24a0c75865c04e8953c49e45904a44f5a9dfb6bc210b42a5b924ee78e788a1",
          "sha1": "b5d1d682e8925740f068a6d014e98d6f586d2942",
          "md5": "62c4029c2f373f625d6b1b21f62af5ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-jpa-i18n-0.1.0-sources.jar",
          "url": "rcm-starter-jpa-i18n-0.1.0-sources.jar",
          "size": 13436,
          "sha512": "904560da688a8c8899b5e8823b75b1ff619bed2da6be633074d13f82b67400a5acb9239e68bcae6e74f49bd63303d3c7b090c799f9c0a63f262fe4ce1512cbea",
          "sha256": "856e0ae14ccb0e17c2f742e9eb092ffdd457db637b98071646a8499b28beb1e7",
          "sha1": "69a39b7f0c81b7f433626f914cadced29ca183ee",
          "md5": "e5949b5a8df3e3ce7698c45c0607aa18"
        }
      ]
    }
  ]
}
