{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-jpa",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-search",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "io.hypersistence",
          "module": "hypersistence-tsid",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0.jar",
          "url": "rcm-starter-jpa-0.1.0.jar",
          "size": 163738,
          "sha512": "3da5ed7ac36e7cfc73de295fbf4751ce467a1c9891ae68289f85a22f39af1d4ecb19d9270031a207b09b16a5f40fda5266225653356da769eec24c9705623e94",
          "sha256": "e54bfb9bd8bf3c3300209e2bcba533ff037210f19225a9c634f7187a83326b95",
          "sha1": "ee692c485ee5b02834d8ac319aa3dd764e73016c",
          "md5": "2ddfb1a8678e2a326128cdb83851a82d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-search",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "io.hypersistence",
          "module": "hypersistence-tsid",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0.jar",
          "url": "rcm-starter-jpa-0.1.0.jar",
          "size": 163738,
          "sha512": "3da5ed7ac36e7cfc73de295fbf4751ce467a1c9891ae68289f85a22f39af1d4ecb19d9270031a207b09b16a5f40fda5266225653356da769eec24c9705623e94",
          "sha256": "e54bfb9bd8bf3c3300209e2bcba533ff037210f19225a9c634f7187a83326b95",
          "sha1": "ee692c485ee5b02834d8ac319aa3dd764e73016c",
          "md5": "2ddfb1a8678e2a326128cdb83851a82d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0-sources.jar",
          "url": "rcm-starter-jpa-0.1.0-sources.jar",
          "size": 135422,
          "sha512": "fba9a61318a5bb8f7072c5188f9d648a9c0ffbeb1683e2867dcca84424a4f19f32ee2c0b689cc9ddd7950400cb46b4bf0f5fecf2d0200428001c50e9d06d5eea",
          "sha256": "807328ddb0237d44be3ba278f60b355b62bf2aef341134bcd325dba319d1dd6b",
          "sha1": "908de9846535fedfac71b099028760a0d23fde96",
          "md5": "f7af495d1767b4e3d029132d67eac302"
        }
      ]
    }
  ]
}
