{
  "formatVersion": "1.1",
  "component": {
    "group": "io.rchemist",
    "module": "rcm-starter-jpa",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-search",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "io.hypersistence",
          "module": "hypersistence-tsid",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0.jar",
          "url": "rcm-starter-jpa-0.1.0.jar",
          "size": 162326,
          "sha512": "ccb6a23cb54aaef78c3524f10e823a5531f42ba2bfcde6af2747ed5dff96168eb51f661b3770769ea68fb5e8238310e91c1c948ee34d2e90ce60a86acb9694a9",
          "sha256": "c34acf279865ce8ade635293d87aef4b3355d7fa8eee14f039b85c02c0b76a74",
          "sha1": "6ee456c5747c87964a94925beea7deb4528bc6e2",
          "md5": "bb8020de9f6436be3fcee01ec722e9e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.rchemist",
          "module": "rcm-framework-bom",
          "version": {
            "requires": "0.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-marker",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-context",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-logging",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-search",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-core-enumtype",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.rchemist",
          "module": "rcm-extension",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "io.hypersistence",
          "module": "hypersistence-tsid",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core"
        }
      ],
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0.jar",
          "url": "rcm-starter-jpa-0.1.0.jar",
          "size": 162326,
          "sha512": "ccb6a23cb54aaef78c3524f10e823a5531f42ba2bfcde6af2747ed5dff96168eb51f661b3770769ea68fb5e8238310e91c1c948ee34d2e90ce60a86acb9694a9",
          "sha256": "c34acf279865ce8ade635293d87aef4b3355d7fa8eee14f039b85c02c0b76a74",
          "sha1": "6ee456c5747c87964a94925beea7deb4528bc6e2",
          "md5": "bb8020de9f6436be3fcee01ec722e9e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rcm-starter-jpa-0.1.0-sources.jar",
          "url": "rcm-starter-jpa-0.1.0-sources.jar",
          "size": 133624,
          "sha512": "f839254b9e49352da26bec49746a8ee742f3318e4996b87b6f0b50952e5e7e7da70ca3e2587b151aa4836ab73e90b6bafb49b80b1840a23becff461f01357e29",
          "sha256": "9894dec1bda2040575ad2360b7d8bb8bff921bfb4b8d6d7db3247cd4c34f75cd",
          "sha1": "a117e6ab9cb85c521d076a586ce7a95e5d12de2e",
          "md5": "498b260fbdb9b080daa629238fe7f0d3"
        }
      ]
    }
  ]
}
